title: "Мій блог"
description: "Мій блог про IT"
remote_theme: "mmistakes/minimal-mistakes@4.27.3"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

collections:
  projects:
    output: true
    permalink: /projects/:name/

header_pages:
  - index.md
  - about.md
  - projects.md
  - contact.md