title: "Мій блог"
description: "Мій блог про IT"
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - index.md
  - about.md
  - contact.md
