title: "PhoenixWay"
description: "Roman Kozak's personal site"
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-feed
  - jekyll-seo-tag

collections:
  projects:
    output: true
    permalink: /projects/:name/

# Menu pages
header_pages:
  - about.md
  - projects.md
  - stack.md  
  - articles.md 
